### ISSUE TITLE
Tutorial out of date?

### ISSUE THREAD

**Issue by mroberts1** [mplusx/hugo-tuflov-theme#1]
I just spent an hour following this tutorial exactly but from a fairly early stage it appears to be out of date.

After editing the theme template and running hugo --verbose, only 4 files are generated, whereas 7 are listed in the tutorial. Specifically,

-rw-r--r--  1 mxu  staff  104 Jun  6 23:35 public/posts/first/index.html
-rw-r--r--  1 mxu  staff  106 Jun  6 23:35 public/posts/second/index.html

are not generated.

As a result, there is nothing available at:

localhost:1313/posts/first/ 

I don't know what the problem is but just wanted to let you know that the tutorial does not work and I was unable to create a new Hugo theme.

**Comment by mengxu00** [comment]
Maybe this Hugo official tutorial could help you come through the initial steps: https://gohugo.io/getting-started/quick-start/
Good luck!
